"""Initialize an audit-grade run directory.

A run is the atomic unit of scientific evidence.
A run is valid only if it contains:
- manifest.json
- checksums.sha256 (after artifacts are generated)

This script creates the run folder and an initial manifest.
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
from pathlib import Path

from hash_utils import environment_fingerprint, save_json


def get_git_commit_hash() -> str:
    """Retrieve the current Git commit hash (HEAD).

    Returns
    -------
    str
        Commit hash or 'UNKNOWN' if unavailable.
    """
    try:
        return (
            subprocess.check_output(["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL)
            .decode("utf-8")
            .strip()
        )
    except Exception:
        return "UNKNOWN"


def generate_run_id() -> str:
    """Generate a unique UTC-based run identifier.

    Returns
    -------
    str
        Run ID in the format YYYYMMDDTHHMMSSZ.
    """
    return dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")


def main(params: dict):
    """Initialize a new reproducible run directory structure.

    Parameters
    ----------
    params : dict
        Dictionary of run parameters to include in the manifest.
    """
    run_id = generate_run_id()
    run_dir = Path("runs") / run_id
    run_dir.mkdir(parents=True, exist_ok=False)

    now_utc = dt.datetime.now(dt.UTC)

    manifest = {
        "run_id": run_id,
        "created_utc": now_utc.isoformat(),
        "git": {
            "repository_url": "https://github.com/ulissesflores/cyberfinancial-resilience-lrblstm",
            "commit": get_git_commit_hash(),
            "tag": None,
        },
        "environment": environment_fingerprint(),
        "parameters": params,
        "artifacts": {
            "data": [],
            "figures": [],
            "metrics": None,
            "checksums_sha256": "checksums.sha256",
            "logs": [],
        },
        "notes": (
            "Run initialized. Artifacts must be generated by subsequent scripts and "
            "added to manifest + checksummed."
        ),
    }

    save_json(manifest, run_dir / "manifest.json")
    print(f"[OK] Run initialized: {run_dir}")
    print(f"[OK] Manifest created: {run_dir / 'manifest.json'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Initialize a reproducible scientific run.")
    parser.add_argument(
        "--note", type=str, default="", help="Optional human-readable note for this run."
    )
    args = parser.parse_args()
    main({"note": args.note})
